### ISSUE TITLE
Single quotes do not convert properly

### ISSUE THREAD

**Issue by li-a** [ldriscoll/Slf4jLogFormatIntentions#3]
## Steps to reproduce

```
log.info("'" + new Object() + "'");
```

## Expected result

```
log.info("'{}'", new Object());
```

## Actual result

```
log.info("\'\'{}\'\'", new Object());
```

Each `'` is doubled and unnecessarily escaped as `\'`.

**Comment by ldriscoll** [comment]
This should be _ok_ now, but also the plugin is deprecated.
