### ISSUE TITLE
How can I format the whole project or the folder the class once instead of one by one?

### ISSUE THREAD

**Issue by manbo1987** [ldriscoll/Slf4jLogFormatIntentions#4]
How can I format the whole project or the folder the class once instead of one by one?

**Comment by ldriscoll** [comment]
Currently the plugin doesn't support batch processing; but it looks like something that intellij supports, so I'll try to look into that.

**Comment by ldriscoll** [comment]
Actually, I'm seeing that this plugin isn't really necessary anymore; in Settings there is `Editor | Inspections | Logging ` there is now `Non-constant string concatenation as argument to logging call`; this supports batch operations

**Comment by manbo1987** [comment]
yes,  it is work fine ,  and use  ctrl alt shift +i  ,  I can find this alert and fix them within seconds,  that help me a lotthank you for your reply -------- 原始邮件 --------发件人： Luke Driscoll <notifications@github.com>日期： 2020年8月26日周三 凌晨1:36收件人： ldriscoll/Slf4jLogFormatIntentions <Slf4jLogFormatIntentions@noreply.github.com>抄送： manbo1987 <manbo1@163.com>, Author <author@noreply.github.com>主    题： Re: [ldriscoll/Slf4jLogFormatIntentions] How can I format the whole project or the folder the class once instead of one by one? (#4)
Actually, I'm seeing that this plugin isn't really necessary anymore; in Settings there is Editor | Inspections | Logging  there is now Non-constant string concatenation as argument to logging call; this supports batch operations

**Comment by ldriscoll** [comment]
Going to close this out, as a wont fix, since the plugin is now deprecated.
